#!/usr/bin/env ruby
# vim:fen:fdm=marker:fmr={{{,}}}:fdl=0:fdc=1:ts=2:sw=2:sts=2:nu

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'gosu'
require 'gosu/all'

class LiveCell < Gosu::Grid::Cell
  def size
    tiles.first.width
  end

  private

  def tiles
    @tiles ||= Gosu::Image.load_tiles(window, 'assets/live_cells.png', 18, 18, true)
  end

  def object
    tiles[Gosu::milliseconds / 50 % tiles.size];
  end
end

class DeadCell < Gosu::Grid::Cell
  def size
    object.width
  end

  private

  def object
    @object ||= Gosu::Image.new(window, 'assets/dead_cell.png', true)
  end
end

class GridGameExample < Gosu::Window
  def initialize
    super(540, 325, false)

    self.caption = "Gosu Grid"

    @grid = Gosu::Grid.new(self)
    @grid.default_cell = DeadCell.new(self, 0, 0)

    @live =  LiveCell.new(self, 5, 6)
    @grid.cells << @live
  end

  def needs_cursor?; true; end

  def button_down(id)
    close if id == Gosu::KbEscape
  end

  def update
    @live.left! if button_down? Gosu::KbLeft
    @live.down! if button_down? Gosu::KbDown
    @live.up! if button_down? Gosu::KbUp
    @live.right! if button_down? Gosu::KbRight
  end

  def draw
    @grid.draw && sleep(0.05)
  end
end

if __FILE__ == $PROGRAM_NAME
  GridGameExample.new.show
end
